---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.openshift.io
  resources:
  - clusterautoscalers
  - machineautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - clusteroperators
  - infrastructures
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  - featuregates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine.openshift.io
  resources:
  - controlplanemachinesets
  - machines
  - machinesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine.openshift.io
  resources:
  - machinehealthchecks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - migration.openshift.io
  resources:
  - vmwarecloudfoundationmigrations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.openshift.io
  resources:
  - vmwarecloudfoundationmigrations/finalizers
  verbs:
  - update
- apiGroups:
  - migration.openshift.io
  resources:
  - vmwarecloudfoundationmigrations/status
  verbs:
  - get
  - patch
  - update
