# Require topology.template for each failure domain. Migration cannot create
# worker MachineSets without an explicit template path on the target vCenter.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vmwarecloudfoundationmigrations.migration.openshift.io
spec:
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              failureDomains:
                items:
                  properties:
                    topology:
                      required:
                      - computeCluster
                      - datacenter
                      - datastore
                      - networks
                      - template
