apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: vcf-migration-console
  namespace: openshift-vcf-migration
spec:
  displayName: VCF Migration
  backend:
    type: Service
    service:
      name: vcf-migration-console-plugin
      namespace: openshift-vcf-migration
      port: 9443
      basePath: /
  proxy:
    - alias: vcf-migration-api
      authorization: UserToken
      endpoint:
        type: Service
        service:
          name: vcf-migration-console-plugin
          namespace: openshift-vcf-migration
          port: 9443
