apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-vcf-migration
resources:
- rbac.yaml
- service.yaml
- deployment.yaml
- consoleplugin.yaml
images:
- name: vcf-migration-console-plugin
  newName: quay.io/jcallen/vcf-migration-console-plugin
  newTag: latest
