apiVersion: v1
kind: ServiceAccount
metadata:
  name: vcf-migration-console-plugin
  namespace: openshift-vcf-migration
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vcf-migration-console-plugin
rules:
  - apiGroups: ["migration.openshift.io"]
    resources: ["vmwarecloudfoundationmigrations"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["machine.openshift.io"]
    resources: ["machinesets", "machines", "controlplanemachinesets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes", "events", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vcf-migration-console-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vcf-migration-console-plugin
subjects:
  - kind: ServiceAccount
    name: vcf-migration-console-plugin
    namespace: openshift-vcf-migration
