apiVersion: v1
kind: Service
metadata:
  name: vcf-migration-console-plugin
  namespace: openshift-vcf-migration
  labels:
    app: vcf-migration-console-plugin
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: vcf-migration-console-plugin-tls
spec:
  ports:
    - port: 9443
      targetPort: 9443
      protocol: TCP
      name: https
  selector:
    app: vcf-migration-console-plugin
