apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/vcf-migration-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: vcf-migration-operator
    appstudio.openshift.io/component: vcf-migration-operator-bundle
    pipelines.appstudio.openshift.io/type: build
  name: vcf-migration-operator-bundle-on-pull-request
  namespace: vcf-migration-operator-tenant
spec:
  params:
  - name: artifact-type
    value: operatorbundle
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/vcf-migration-operator-tenant/vcf-migration-operator/vcf-migration-operator-bundle-main:on-pr-{{revision}}
  - name: dockerfile
    value: bundle.konflux.Dockerfile
  - name: path-context
    value: .
  - name: build-platforms
    value:
    - "linux/amd64"
  - name: image-expires-after
    value: 5d
  - name: hermetic
    value: "true"
  - name: prefetch-input
    value: ""
  - name: build-source-image
    value: "true"
  pipelineRef:
    name: vcf-migration-operator-bundle-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-vcf-migration-operator-bundle
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}